name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14", "16"]
    name: Node ${{ matrix.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: npm install
      - name: Type Check
        run: npm run typecheck
      - name: Test
        run: npm test
      - name: Lint
        run: npx prettier --check .
      - name: Circular dependency check
        uses: gerrit0/circular-dependency-check@v1
        with:
          entry: index.js
